CREATE TABLE `players` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`player` VARCHAR(50) NULL DEFAULT NULL,
	`team` CHAR(3) NULL DEFAULT NULL,
	`number` TINYINT(4) NULL DEFAULT NULL,
	`position1` CHAR(2) NULL DEFAULT NULL,
	`position2` CHAR(2) NULL DEFAULT NULL,
	`height` INT(11) NULL DEFAULT NULL,
	`weight` INT(11) NULL DEFAULT NULL,
	`country` VARCHAR(50) NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
)